name:                advent-of-code2016-haskell
version:             0.1.0.0
github:              "szwester/advent-of-code-2016-haskell"
license:             BSD3
author:              "Szwester"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code2016-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:

  day-01:
    main:                Solution.hs
    source-dirs:         app/day-01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    

  day-02:
    main:                Solution.hs
    source-dirs:         app/day-02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    

  day-03:
    main:                Solution.hs
    source-dirs:         app/day-03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - split

  day-04:
    main:                Solution.hs
    source-dirs:         app/day-04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers

  day-05:
    main:                Solution.hs
    source-dirs:         app/day-05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pureMD5
    - bytestring

  day-06:
    main:                Solution.hs
    source-dirs:         app/day-06
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers

  day-07:
    main:                Solution.hs
    source-dirs:         app/day-07
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers

  day-08:
    main:                Solution.hs
    source-dirs:         app/day-08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    
  
  day-09:
    main:                Solution.hs
    source-dirs:         app/day-09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    

  day-10:
    main:                Solution.hs
    source-dirs:         app/day-10
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  day-11:
    main:                Solution.hs
    source-dirs:         app/day-11
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - split
    - containers

  day-12:
    main:                Solution.hs
    source-dirs:         app/day-12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    
    dependencies:
    - containers

  day-13:
    main:                Solution.hs
    source-dirs:         app/day-13
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    
    dependencies:
    - containers

  day-14:
    main:                Solution.hs
    source-dirs:         app/day-14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    
    dependencies:
    - pureMD5

  day-15:
    main:                Solution.hs
    source-dirs:         app/day-15
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  day-16:
    main:                Solution.hs
    source-dirs:         app/day-16
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  day-17:
    main:                Solution.hs
    source-dirs:         app/day-17
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pureMD5

  day-18:
    main:                Solution.hs
    source-dirs:         app/day-18
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers

  day-19:
    main:                Solution.hs
    source-dirs:         app/day-19
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers

tests:
  advent-of-code2016-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code2016-haskell
